openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab №2 Example API'
  description: API для сервиса поездок с попутчиками 
servers:
  - url: http://localhost:8080
    description: Example server
paths:
# =========================================================================== # 
  /auth: # проверка авторизации
    get:
      summary: Проверка аутентификации
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not authentication
          content:
            application/json:
              schema:
                type: string
  # =========================================================================== # 
  /user: # поиск по айди
    get:
      summary: Чтение информации о пользователе
      parameters:
      - name: id
        description: Уникальный идентификатор пользователя
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового пользователя
      parameters:
      - name: first_name
        description: Имя пользователя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия пользователя
        in: query
        required: true
        schema:
          type: string
      - name: email
        description: email пользователя
        in: query
        required: true
        schema:
          type: string
      - name: phone
        description: номер телефона пользователя 
        in: query
        required: true
        schema:
          type: string
      - name: login
        description: login пользователя
        in: query
        required: true
        schema:
          type: string
      - name: password
        description: пароль пользователя
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  # =========================================================================== # 
  /user/search/fio: # поиск по фио (работает)
    get:
      servers:
        - url: http://localhost:8080
      summary: Поиск пользователей по маске имени и фамилии
      parameters:
      - name: first_name
        description: Имя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: The users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No user found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  # =========================================================================== # 
  /user/search/login: # поиск по логину (работает)
    get:
      servers:
        - url: http://localhost:8080
      summary: Поиск пользователя по логину
      parameters:
      - name: login
        description: Логин
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: Пользователь с соответствующим логином
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: Пользователь с таким логином не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Непредвиденная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
  # ==============================TRIPS============================================= # 
  /trips:
    get: #п.8 получить инфу о поездке (работает)
      servers:
        - url: http://localhost:8082
      summary: Получение информации о поездке
      parameters:
      - name: id
        description: Идентификатор поездки
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/trip_id'
      responses:
        200:
          description: Найденная поездка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trip'
        404:
          description: Поездка не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post: # п.6 Создание поездки (работает)
      servers:
        - url: http://localhost:8082
      summary: Добавление новой поездки 
      parameters:
      - name: route_ID
        description: Идентификатор маршрута
        in: query
        required: true
        schema:
            $ref: '#/components/schemas/id_route'
      - name: driver
        description: Идентификатор водителя 
        in: query
        required: true
        schema:
          type: integer  
      # - name: user
      #   description: Идентификатор пользователя 
      #   in: query
      #   required: true
      #   schema:
      #       $ref: '#/components/schemas/user_id'
      - name: date_depart
        description: Дата отправления 
        in: query
        required: true
        schema:
          type: string
      - name: travel_conditions
        description: Пожелания к поездке 
        in: query
        required: true
        schema:
          type: string
      - name: price
        description: Стоимость поездки 
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Идентификатор добавленной поездки
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления поездки
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 

  /connect:
   post: # п.7 Подключение пользователя к поездке (в разработке)
      servers:
        - url: http://localhost:8082
      summary: Подключение пользователя к поездке 
      parameters:
      - name: user_id
        description: Идентификатор пользователя
        in: query
        required: true
        schema:
            $ref: '#/components/schemas/user_id'
      - name: trip_id
        description: Идентификатор поездки 
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/trip_id'   
      responses:
        '200':
          description: Идентификатор добавленной поездки
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления поездки
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
  # ================================= ROUTE ========================================== # 
  /routes: # получение информации о маршрутах пользователя
    get:
      servers:
        - url: http://localhost:8081
      summary: Информации о маршрутах пользователя
      parameters:
      - name: id_user
        description: Идентификатор маршрута
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        200:
          description: Найденный маршрут
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/route'
        404:
          description: Маршрут не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post: # п.4 Создание маршрута
      servers:
        - url: http://localhost:8081
      summary: Добавление нового маршрута
      parameters:
      # - name: id_route
      #   description: Идентификатор маршрута
      #   in: query
      #   required: true
      #   schema:
      #       $ref: '#/components/schemas/id_route'
      - name: id_user
        description: Идентификатор пользователя 
        in: query
        required: true
        schema:
            $ref: '#/components/schemas/user_id'
      - name: point_start
        description: Город отправления 
        in: query
        required: true
        schema:
          type: string
      - name: point_end
        description: Город прибытия 
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор добавленного маршрута
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления маршрута
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

# ============================= COMPONENTS SCHEMAS ============================
components:
  schemas:
    user_id:
      description: Уникальный идентификатор пользователя
      type: integer
    id_route:
      description: Уникальный идентификатор маршрута
      type: integer
    trip_id:
      description: Уникальный идентификатор поездки
      type: integer
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    trips:
      type: array
      items:
        $ref: '#/components/schemas/trip'
    user:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - phone
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        phone:
          type: string
        login:
          type: string
        password:
          type: string
# ===================================== trip object ============================== #
    trip:
      type: object
      required:
        - id_route
        - driver
        - user
        - date_depart
        - travel_conditions
        - price
      properties:
        id_route:
          $ref: '#/components/schemas/id_route'
        driver:
          $ref: '#/components/schemas/user_id'
        user:
          $ref: '#/components/schemas/user_id'
        date_depart:
          type: string
          description: Дата отправки
        travel_conditions:
          type: string
          description: Пожелания по поездке
        price:
          type: integer
          description: Стоимость поездки
# ===================================== route object ============================== #
    route:
      type: object
      required:
        - id_route
        - id_user
        - point_start
        - point_end
      properties:
        id_route:
          $ref: '#/components/schemas/id_route'
        id_user:
          $ref: '#/components/schemas/user_id'
        point_start:
          type: string
          description: Город отправления
        description:
          type: string
          description: Город прибытия
        format:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []